#ifndef CONFIG_H
#define CONFIG_H

#define BAUD_RATE 115200 

#define MAX_SPEED 100
#define MAX_SPEED_REVERS -100

#define BUTTON_REFRESH_TIME 100

#define BUTTON_PLUS 6
#define BUTTON_MINUS 5
#define BUTTON_STOP 8
#define BUTTON_RESERVED 9

#define MOTOR_PIN_1 2
#define MOTRO_PIN_2 3
#define MOTRO_PWN 10

#define DISPLAY_ROWS 4
#define DISPLAY_COLS 20
#define DISPLAY_ADRESS 0x27

#endif // CONFIG_H